[project]
name = "flab-decode-jackpot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "selenium>=4.36.0",
    "webdriver-manager>=4.0.2",
]
